### ISSUE TITLE
Resolve GBIF name matching

### ISSUE THREAD

**Issue by peterdesmet** [inbo/red-lists-flanders#1]
Note: @stijnvanhoey can you upload matched species list?

We still need to resolve GBIF name matching for 8 species:

| Speciesname | kingdom |
| --- | --- |
| Arvicola amphibius/scherman | Animalia |
| Oenopia impustulata | Animalia |
| Carex viridula s.l. | Plantae |
| Pyrus pyraster (L.) Duroi | Plantae |
| Carabus arvensis sylvaticus | Animalia |
| Henosepilachna argus | Animalia |
| Lotus corniculatus L. subsp. tenuis (Waldst. et Kit. ex Willd.) Berher | Plantae |
| Sorex araneus/coronatus | Animalia |

**Comment by DimEvil** [comment]
Most of the names do match when using the GBIF portal. For some the scientificName was not properly formulated, s.l. was used or '/' was used.

Some species are indeed not in the GBIF tax backbone, but in other ones.

http://www.gbif.org/species/4265185  Arvicola amphibius   (sherman -> no match)
http://www.gbif.org/species/123363450  Oenopia impostulata  (Idd Enkel Fauna Europaea) Not in GBIF tax backbone

http://www.gbif.org/species/8234720  Carex viridula wel  (NONE Multiple equal matches for Carex viridula)  Carex viridula s.l. (geen match alzo)

http://www.gbif.org/species/7529983  Pyrus pyraster ook wel (NONE No match because of too little confidence)  (Auteur L. Boreau in GBIF en niet L. Duroi --> typo's???)  Too many options here.

http://www.gbif.org/species/4470987 Carabus arvensis sylvaticus (Synonym of Carabus irregularis?)  (http://carabidae.org/taxa/arvensis-sylvaticus-dejean-1826)

Henosepilachna argus -->  Subcoccinella vigintiquatuorpunctata  ???  GBIF geeft deze als antwoord op Henosepilachna

http://www.gbif.org/species/8673752  Lotus corniculatus subsp. tenuis (formulation not correct?)

http://www.gbif.org/species/8316400  Sorex araneus

http://www.gbif.org/species/2436090  Sorex coronatus

**Comment by peterdesmet** [comment]
To check if an **unmatched** name is in Fauna Europaea, use:

> http://api.gbif.org/v1/species?name=Vulpes+vulpes&datasetKey=90d9e8a6-0ce1-472d-b682-3451095dbc5a

Note: you **cannot use the GBIF name matching** for this, as this only uses the GBIF backbone taxonomy.

To check if a **matched** name (i.e. you know the nubKey) is in Fauna Europaea, use:

> http://api.gbif.org/v1/species/5219243/related?datasetKey=90d9e8a6-0ce1-472d-b682-3451095dbc5a

**Comment by peterdesmet** [comment]
Closing issue, as name matching will be done again + dataset has moved to https://github.com/inbo/data-publication/tree/master/datasets/rl-flanders-checklist
